spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: auth-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**

        - id: users-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: department-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/departments/**

        - id: citizen-service
          uri: lb://CITIZEN-SERVICE
          predicates:
            - Path=/citizens/**

        - id: officer-service
          uri: lb://OFFICER-SERVICE
          predicates:
            - Path=/officers/**

        - id: grievance-service
          uri: lb://GRIEVANCE-SERVICE
          predicates:
            - Path=/grievances/**

        - id: welfare-service
          uri: lb://WELFARE-SERVICE
          predicates:
            - Path=/welfare/**,/applications/**,/schemes/**,/documents/**,/beneficiaries/**

        - id: reporting-service
          uri: lb://REPORTING-SERVICE
          predicates:
            - Path=/reports/**

        - id: certificate-service
          uri: lb://CERTIFICATE-SERVICE
          predicates:
            - Path=/certificates/**
        - id: budget-service
          uri: lb://BUDGET-SERVICE
          predicates:
            - Path=/budgets/**
        - id: audit-service
          uri: lb://AUDIT-SERVICE
          predicates:
            - Path=/audit/**
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**
        - id: service-management-service
          uri: lb://SERVICE-MANAGEMENT-SERVICE
          predicates:
            - Path=/services/**
        - id: ai-analysis-service
          uri: lb://AI-ANALYSIS-SERVICE
          predicates:
            - Path=/ai/**
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

  instance:
    prefer-ip-address: false
    hostname: api-gateway
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG