spring.application.name=officer-service

server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5432/officer_db
spring.datasource.username=postgres
spring.datasource.password=3112

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=false
eureka.instance.hostname=officer-service
eureka.instance.instance-id=${spring.application.name}:${server.port}

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
