spring.application.name=welfare-service

server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5432/civicpulse
spring.datasource.username=postgres
spring.datasource.password=3112

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=false
eureka.instance.hostname=welfare-service
eureka.instance.instance-id=${spring.application.name}:${server.port}

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=true